### ISSUE TITLE
Can't create new sitemap

### ISSUE THREAD

**Issue by Sifizu** [rainlab/sitemap-plugin#54]
Hi!
I installed your sitemap plugin to my project, but when I tried to add a sitemap, nothing has happend. As I checked in the inspector, some JS files drops error 404. Any ideas what can I do?

**Comment by LukeTowers** [comment]
> some JS files drops error 404.

Well, that's very helpful. *cough* *cough*

The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.

**Comment by mikemunger** [comment]
@Sifizu I just experienced this myself, I had to rerun php artisan october:mirror <public_dir> after installing the plugin - that is, if you use a public folder: https://octobercms.com/docs/setup/configuration#public-folder
