### ISSUE TITLE
Reordering feature not working properly

### ISSUE THREAD

**Issue by scanzy** [rainlab/sitemap-plugin#66]
Hi, I've been experiencing issues when trying to reorder items.
The problem occurs only if the list is bigger than the page (and the scrolling bar appears). For example if the page can show 10 list elements, there are problems reordering all the elements from the 11th.
It looks like the plugin doesn't take into account the scroll position of the list.

Thanks in advance

**Comment by w20k** [comment]
@scanzy could you provide a screenshot or gif of this issue? This might be a core problem, needs testing.

**Comment by scanzy** [comment]
As you can see in the screenshots, when the scrollbar is all the way up everything is working fine, so the grey element (new item position) is right under the light blue one (grabbed by the mouse).

![schermata da 2019-02-21 12-36-25](https://user-images.githubusercontent.com/13015360/53166930-da1b3380-35d6-11e9-9ef2-271ab818d0fa.png)

The more I scroll down the list, the more the distance between the gray element and the light blue one

![schermata da 2019-02-21 12-36-51](https://user-images.githubusercontent.com/13015360/53167003-fdde7980-35d6-11e9-9a4a-0dbcbfa6b388.png)

![schermata da 2019-02-21 12-37-06](https://user-images.githubusercontent.com/13015360/53167005-02a32d80-35d7-11e9-9d95-dc7e36a399c7.png)

![schermata da 2019-02-21 12-37-14](https://user-images.githubusercontent.com/13015360/53167009-0636b480-35d7-11e9-952f-33fb71a51094.png)

Also, I am noticing that strange grey rectangle on the right, what is it for?

**Comment by w20k** [comment]
@scanzy thanks a lot for screenshots. Grey thing is a scroll bar ;)
And most probably it's a core issue, more specifically with this plugin: https://github.com/johnny/jquery-sortable

**Comment by RCheesley** [comment]
I also experienced this problem as my sitemap got longer .. super frustrating!

**Comment by w20k** [comment]
We need to fix the old jQuery plugin for the solo case. I don't have time for that at the moment.

**Comment by LukeTowers** [comment]
@RCheesley @scanzy if you guys want you can always work on a fix yourself and then submit it to the core in a PR, or you can feel free to sponsor the issue / have your company's sponsor it so that it would get dealt with sooner. 

For what it's worth, I've also encountered the issue, so we know it's a bug, it just hasn't annoyed me personally enough yet to care about spending time on fixing it, but if it's reached that point for someone else - great! Issues only get dealt with by people that care about resolving them, so for an issue to get fixed, that has to be someone 😉

**Comment by daftspunk** [comment]
This should have been fixed as part of https://github.com/rainlab/pages-plugin/issues/384

Thanks
