### ISSUE TITLE
Implement urls with the language tag

### ISSUE THREAD

**Issue by HermesZum** [rainlab/sitemap-plugin#75]
Google recommends using different URLs for each language version of a page rather than using cookies or browser settings to adjust the content language on the page.

It will be possible to implement urls with the language tag?

Regards

**Comment by LukeTowers** [comment]
There's been a few different issues / PRs on this between this plugin and the rainlab.translate plugin. It is something we're open to supporting but it kind of petered out because I didn't have time to implement it how I wanted it and the person proposing didn't have time to revise it from their initial approach.

**Comment by HermesZum** [comment]
I understand that there are several priorities when designing a CMS. However, sitemap is an essential component of CMS SEO. I think that being a RainLab component it should be complete. I am testing the October CMS to see if it is a viable solution. So far I'm enjoying it, October CMS a lot of potential, but I came across problems like this, an essential component that does not fit for multilanguage websites. I will wait for a resolution, but I saw that this is a problem with a few years.

**Comment by LukeTowers** [comment]
The original author of the PR to add support just ended up creating their own plugin to handle this need: https://octobercms.com/plugin/utopigs-seo, so you could always use that instead. The reason it hasn't been properly implemented in the rainlab plugin yet is that no one wanted to implement the suggested changes, the core team who could relatively easily implement them doesn't really use multilanguage sites a lot so it doesn't come up as a daily issue for them, and thus far no one has been willing to sponsor the addition. If you'd like to sponsor the addition, I could look into the issues again and come up with a robust solution for the RainLab.Sitemap plugin for $300 USD. Otherwise I'd recommend you take a look at the other plugin I linked.
