### ISSUE TITLE
Empty sitemap.xml

### ISSUE THREAD

**Issue by sozonovalexey** [rainlab/sitemap-plugin#8]
Hello! I tried to add custom url or page to sitemap but file still empty...

**Comment by mighty-code** [comment]
Same Issue on my projects. If I reload the page in backend where i added the pages to the sitemap.xml it will be empty again... 

If I add and save I'll get a succes alert....

**Comment by SaifurRahmanMohsin** [comment]
Had the same issue but fixed by downloading the repo into my October install. I think the hook failed to push the updated copy to OctoberCMS.com. Here's a script to get it quickly. Just cd into your October folder using SSH, copy the entire paste and paste it into the terminal
`http://laravel.io/bin/nQ2xd`

**Comment by sozonovalexey** [comment]
Last update solved the problem.
